### ISSUE TITLE
Error with Dockerfile

### ISSUE THREAD

**Issue by haedrichowen** [mmjee/pm-docker#1]
```
[+] Building 17.9s (11/14)                                  docker:default
 => [internal] load .dockerignore                                     0.0s
 => => transferring context: 2B                                       0.0s
 => [internal] load build definition from Dockerfile                  0.0s
 => => transferring dockerfile: 713B                                  0.0s
 => [internal] load metadata for docker.io/library/nginx:alpine       0.2s
 => [internal] load metadata for docker.io/library/node:lts-alpine    0.2s
 => [internal] load build context                                     0.0s
 => => transferring context: 32B                                      0.0s
 => [build 1/6] FROM docker.io/library/node:lts-alpine@sha256:cb2301  0.0s
 => => resolve docker.io/library/node:lts-alpine@sha256:cb2301e2c5fe  0.0s
 => CACHED [stage-1 1/3] FROM docker.io/library/nginx:alpine@sha256:  0.0s
 => CACHED [build 2/6] WORKDIR /app/                                  0.0s
 => CACHED [build 3/6] RUN --mount=type=cache,target=/var/cache/apk   0.0s
 => CACHED [build 4/6] RUN git clone --depth 1 --branch master https  0.0s
 => ERROR [build 5/6] RUN yarn add @achrinza/node-ipc@9.2.8          17.6s
------                                                                     
 > [build 5/6] RUN yarn add @achrinza/node-ipc@9.2.8:                      
0.486 yarn add v1.22.19                                                    
0.587 [1/4] Resolving packages...                                          
1.642 [2/4] Fetching packages...                                           
17.26 error @achrinza/node-ipc@9.2.5: The engine "node" is incompatible with this module. Expected version "8 || 9 || 10 || 11 || 12 || 13 || 14 || 15 || 16 || 17 || 18". Got "20.9.0"
17.27 error Found incompatible module.
17.27 info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
------
Dockerfile:16
--------------------
  14 |     ENV VUE_APP_EDS_URL=${EDS_URL}
  15 |     
  16 | >>> RUN yarn add @achrinza/node-ipc@9.2.8
  17 |     RUN --mount=type=cache,target=/root/.cache/yarn \
  18 |         --mount=type=cache,target=/app/node_modules \
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn add @achrinza/node-ipc@9.2.8" did not complete successfully: exit code: 1
```

**Comment by mmjee** [comment]
On Thursday, November 23 2023 Anno Domini 04:05 AM India Standard Time, haedrichowen wrote:
> `[+] Building 17.9s (11/14)                                  docker:default
>  => [internal] load .dockerignore                                     0.0s
>  => => transferring context: 2B                                       0.0s
>  => [internal] load build definition from Dockerfile                  0.0s
>  => => transferring dockerfile: 713B                                  0.0s
>  => [internal] load metadata for docker.io/library/nginx:alpine       0.2s
>  => [internal] load metadata for docker.io/library/node:lts-alpine    0.2s
>  => [internal] load build context                                     0.0s
>  => => transferring context: 32B                                      0.0s
>  => [build 1/6] FROM ***@***.***:cb2301  0.0s
>  => => resolve ***@***.***:cb2301e2c5fe  0.0s
>  => CACHED [stage-1 1/3] FROM ***@***.***:  0.0s
>  => CACHED [build 2/6] WORKDIR /app/                                  0.0s
>  => CACHED [build 3/6] RUN --mount=type=cache,target=/var/cache/apk   0.0s
>  => CACHED [build 4/6] RUN git clone --depth 1 --branch master https  0.0s
>  => ERROR [build 5/6] RUN yarn add @***@***.***          17.6s
> ------                                                                     
>  > [build 5/6] RUN yarn add @***@***.***:                      
> 0.486 yarn add v1.22.19                                                    
> 0.587 [1/4] Resolving packages...                                          
> 1.642 [2/4] Fetching packages...                                           
> 17.26 error @***@***.***: The engine "node" is incompatible with this module. Expected version "8 || 9 || 10 || 11 || 12 || 13 || 14 || 15 || 16 || 17 || 18". Got "20.9.0"
> 17.27 error Found incompatible module.
> 17.27 info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
> ------
> Dockerfile:16
> --------------------
>   14 |     ENV VUE_APP_EDS_URL=${EDS_URL}
>   15 |     
>   16 | >>> RUN yarn add @***@***.***
>   17 |     RUN --mount=type=cache,target=/root/.cache/yarn \
>   18 |         --mount=type=cache,target=/app/node_modules \
> --------------------
> ERROR: failed to solve: process "/bin/sh -c yarn add @***@***.***" did not complete successfully: exit code: 1`
> 
I just pushed a commit to fix this problem. Can you try this out again?

See: https://github.com/mmjee/pm-docker/commit/cfb5c5d7a8e1bb8b95eb8b35eefdbdbb62052921
-- 
Regards,

**Comment by mmjee** [comment]
Assuming the commit above fixed the problem, closing the issue. Feel free to reopen if this is still a problem.
