### ISSUE TITLE
Yarn Install Failure During Container Build

### ISSUE THREAD

**Issue by alakameljebali** [mmjee/pm-docker#3]
**Description:**
During the Docker build process, an unexpected error occurs while executing yarn install. The error message indicates a failure to fetch a package from a specific URL (https://cf-ipfs.com/ipfs/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX?filename=noto-sans-cjk-webfont.tgz). The error status code is "524 undefined".

**Steps to Reproduce:**

1. Clone the repository containing the Dockerfile.
2. Run the Docker build command (podman build -t <image_name> .).
3. Observe the error during the execution of yarn install in the Docker build process.

**Expected Behavior:**
The yarn install command should successfully fetch and install the required packages without encountering any errors, allowing the Docker build process to complete successfully.

**Actual Behavior:**
The yarn install command fails to fetch a package from the specified URL (https://cf-ipfs.com/ipfs/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX?filename=noto-sans-cjk-webfont.tgz), resulting in a build failure with a "Request failed" error and a status code of "524 undefined".

**Comment by mmjee** [comment]
On Monday, February 12 2024 Anno Domini 01:02 AM India Standard Time, Alaeddine Jebali wrote:
> **Description:**
> During the Docker build process, an unexpected error occurs while executing yarn install. The error message indicates a failure to fetch a package from a specific URL (https://cf-ipfs.com/ipfs/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX?filename=noto-sans-cjk-webfont.tgz). The error status code is "524 undefined".
> 
> **Steps to Reproduce:**
> 
> 1. Clone the repository containing the Dockerfile.
> 2. Run the Docker build command (podman build -t <image_name> .).
> 3. Observe the error during the execution of yarn install in the Docker build process.
> 
> **Expected Behavior:**
> The yarn install command should successfully fetch and install the required packages without encountering any errors, allowing the Docker build process to complete successfully.
> 
> **Actual Behavior:**
> The yarn install command fails to fetch a package from the specified URL (https://cf-ipfs.com/ipfs/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX?filename=noto-sans-cjk-webfont.tgz), resulting in a build failure with a "Request failed" error and a status code of "524 undefined".
> 
This is primarily because downloading the package from IPFS timed out. Re-attempting the build should succeed (hopefully) because it'll be in the cache by then. 
Unfortunately, the packages are single-homed on my IPFS node as of now, so it'll have to be this way.
I'll reconsider alternatives to IPFS, but there's nothing decentralized like IPFS right now.
-- 
Regards,

**Comment by mmjee** [comment]
BTW, the dependencies were moved to Backblaze B2 from IPFS, so this should no longer be an issue.
